// Demo inventory data - All 70 items (35 rural + 35 urban)
// This file is used to populate inventory pages when Supabase is unavailable

import type { Inventory } from '@/types/types';

export const DEMO_RURAL_INVENTORY: Inventory[] = [
  // SEEDS (5 items)
  {
    id: 'rural-001',
    owner_id: 'demo-rural',
    item_name: 'Hybrid Tomato Seeds (F1)',
    category: 'Seeds',
    quantity: 25,
    unit: 'kg',
    reorder_threshold: 50,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-002',
    owner_id: 'demo-rural',
    item_name: 'Mung Bean Seeds (Hybrid)',
    category: 'Seeds',
    quantity: 40,
    unit: 'kg',
    reorder_threshold: 60,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-003',
    owner_id: 'demo-rural',
    item_name: 'Potato Seed',
    category: 'Seeds',
    quantity: 100,
    unit: 'kg',
    reorder_threshold: 80,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-004',
    owner_id: 'demo-rural',
    item_name: 'Cabbage Seeds',
    category: 'Seeds',
    quantity: 15,
    unit: 'kg',
    reorder_threshold: 20,
    created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-005',
    owner_id: 'demo-rural',
    item_name: 'Chili Pepper Seeds',
    category: 'Seeds',
    quantity: 12,
    unit: 'kg',
    reorder_threshold: 15,
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // FERTILIZERS (6 items)
  {
    id: 'rural-006',
    owner_id: 'demo-rural',
    item_name: 'NPK 10-26-26 Fertilizer',
    category: 'Fertilizers',
    quantity: 150,
    unit: 'kg',
    reorder_threshold: 100,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-007',
    owner_id: 'demo-rural',
    item_name: 'Urea (46% Nitrogen)',
    category: 'Fertilizers',
    quantity: 75,
    unit: 'kg',
    reorder_threshold: 100,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-008',
    owner_id: 'demo-rural',
    item_name: 'Vermicompost',
    category: 'Fertilizers',
    quantity: 300,
    unit: 'kg',
    reorder_threshold: 150,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-009',
    owner_id: 'demo-rural',
    item_name: 'Calcium Nitrate',
    category: 'Fertilizers',
    quantity: 60,
    unit: 'kg',
    reorder_threshold: 50,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-010',
    owner_id: 'demo-rural',
    item_name: 'Micronutrient Mix (Zn, Fe, Cu)',
    category: 'Fertilizers',
    quantity: 45,
    unit: 'kg',
    reorder_threshold: 40,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-011',
    owner_id: 'demo-rural',
    item_name: 'DAP (Diammonium Phosphate)',
    category: 'Fertilizers',
    quantity: 85,
    unit: 'kg',
    reorder_threshold: 70,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // PESTICIDES (4 items)
  {
    id: 'rural-012',
    owner_id: 'demo-rural',
    item_name: 'Neem Oil (Bio-pesticide)',
    category: 'Pesticides',
    quantity: 35,
    unit: 'liters',
    reorder_threshold: 40,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-013',
    owner_id: 'demo-rural',
    item_name: 'Copper Sulfate Fungicide',
    category: 'Pesticides',
    quantity: 18,
    unit: 'kg',
    reorder_threshold: 25,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-014',
    owner_id: 'demo-rural',
    item_name: 'Pyrethrin Insecticide',
    category: 'Pesticides',
    quantity: 12,
    unit: 'liters',
    reorder_threshold: 15,
    created_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-015',
    owner_id: 'demo-rural',
    item_name: 'Sulfur Powder (Fungicide)',
    category: 'Pesticides',
    quantity: 28,
    unit: 'kg',
    reorder_threshold: 30,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // TOOLS (4 items)
  {
    id: 'rural-016',
    owner_id: 'demo-rural',
    item_name: 'Spading Fork',
    category: 'Tools',
    quantity: 8,
    unit: 'units',
    reorder_threshold: 5,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-017',
    owner_id: 'demo-rural',
    item_name: 'Mulching Cloth',
    category: 'Tools',
    quantity: 150,
    unit: 'sq.m',
    reorder_threshold: 100,
    created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-018',
    owner_id: 'demo-rural',
    item_name: 'Digging Hoe',
    category: 'Tools',
    quantity: 12,
    unit: 'units',
    reorder_threshold: 8,
    created_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-019',
    owner_id: 'demo-rural',
    item_name: 'Pruning Shears',
    category: 'Tools',
    quantity: 10,
    unit: 'units',
    reorder_threshold: 7,
    created_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // IRRIGATION (2 items)
  {
    id: 'rural-020',
    owner_id: 'demo-rural',
    item_name: 'Drip Irrigation Tape',
    category: 'Irrigation',
    quantity: 250,
    unit: 'meters',
    reorder_threshold: 200,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-021',
    owner_id: 'demo-rural',
    item_name: 'Garden Hose (25mm)',
    category: 'Irrigation',
    quantity: 6,
    unit: 'units',
    reorder_threshold: 4,
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // EQUIPMENT (4 items)
  {
    id: 'rural-022',
    owner_id: 'demo-rural',
    item_name: 'Water Pump (1 HP)',
    category: 'Equipment',
    quantity: 2,
    unit: 'units',
    reorder_threshold: 1,
    created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-023',
    owner_id: 'demo-rural',
    item_name: 'Power Sprayer',
    category: 'Equipment',
    quantity: 3,
    unit: 'units',
    reorder_threshold: 2,
    created_at: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-024',
    owner_id: 'demo-rural',
    item_name: 'Tiller (2 HP)',
    category: 'Equipment',
    quantity: 1,
    unit: 'units',
    reorder_threshold: 1,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-025',
    owner_id: 'demo-rural',
    item_name: 'Pesticide Sprayer Pump',
    category: 'Equipment',
    quantity: 7,
    unit: 'units',
    reorder_threshold: 5,
    created_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // STORAGE (2 items)
  {
    id: 'rural-026',
    owner_id: 'demo-rural',
    item_name: 'Plastic Storage Bins (50L)',
    category: 'Storage',
    quantity: 35,
    unit: 'units',
    reorder_threshold: 25,
    created_at: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-027',
    owner_id: 'demo-rural',
    item_name: 'Burlap Sacks (50kg)',
    category: 'Storage',
    quantity: 200,
    unit: 'units',
    reorder_threshold: 150,
    created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // HARVESTING (2 items)
  {
    id: 'rural-028',
    owner_id: 'demo-rural',
    item_name: 'Harvesting Baskets',
    category: 'Harvesting',
    quantity: 25,
    unit: 'units',
    reorder_threshold: 20,
    created_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-029',
    owner_id: 'demo-rural',
    item_name: 'Harvesting Knife/Sickle',
    category: 'Harvesting',
    quantity: 18,
    unit: 'units',
    reorder_threshold: 12,
    created_at: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // SAFETY (3 items)
  {
    id: 'rural-030',
    owner_id: 'demo-rural',
    item_name: 'Protective Gloves (Nitrile)',
    category: 'Safety',
    quantity: 500,
    unit: 'pairs',
    reorder_threshold: 300,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-031',
    owner_id: 'demo-rural',
    item_name: 'N95 Masks',
    category: 'Safety',
    quantity: 250,
    unit: 'units',
    reorder_threshold: 200,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-032',
    owner_id: 'demo-rural',
    item_name: 'Safety Boots (Size 10)',
    category: 'Safety',
    quantity: 8,
    unit: 'pairs',
    reorder_threshold: 5,
    created_at: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // SOIL AMENDMENTS (2 items)
  {
    id: 'rural-033',
    owner_id: 'demo-rural',
    item_name: 'Gypsum (Calcium Sulfate)',
    category: 'Soil Amendments',
    quantity: 120,
    unit: 'kg',
    reorder_threshold: 100,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rural-034',
    owner_id: 'demo-rural',
    item_name: 'Limestone (pH Adjuster)',
    category: 'Soil Amendments',
    quantity: 500,
    unit: 'kg',
    reorder_threshold: 400,
    created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OTHER (1 item)
  {
    id: 'rural-035',
    owner_id: 'demo-rural',
    item_name: 'Twine/String (100m roll)',
    category: 'Other',
    quantity: 15,
    unit: 'rolls',
    reorder_threshold: 10,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_URBAN_INVENTORY: Inventory[] = [
  // SEEDS (5 items)
  {
    id: 'urban-001',
    owner_id: 'demo-urban',
    item_name: 'Cherry Tomato Seeds',
    category: 'Seeds',
    quantity: 8,
    unit: 'packets',
    reorder_threshold: 10,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-002',
    owner_id: 'demo-urban',
    item_name: 'Lettuce Seeds (Mixed)',
    category: 'Seeds',
    quantity: 12,
    unit: 'packets',
    reorder_threshold: 10,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-003',
    owner_id: 'demo-urban',
    item_name: 'Herb Seeds Variety Pack',
    category: 'Seeds',
    quantity: 15,
    unit: 'packets',
    reorder_threshold: 12,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-004',
    owner_id: 'demo-urban',
    item_name: 'Bell Pepper Seeds',
    category: 'Seeds',
    quantity: 6,
    unit: 'packets',
    reorder_threshold: 8,
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-005',
    owner_id: 'demo-urban',
    item_name: 'Spinach Seeds',
    category: 'Seeds',
    quantity: 10,
    unit: 'packets',
    reorder_threshold: 8,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // CONTAINERS (5 items)
  {
    id: 'urban-006',
    owner_id: 'demo-urban',
    item_name: 'Ceramic Pots (8cm)',
    category: 'Containers',
    quantity: 20,
    unit: 'units',
    reorder_threshold: 25,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-007',
    owner_id: 'demo-urban',
    item_name: 'Ceramic Pots (15cm)',
    category: 'Containers',
    quantity: 15,
    unit: 'units',
    reorder_threshold: 20,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-008',
    owner_id: 'demo-urban',
    item_name: 'Plastic Hanging Baskets',
    category: 'Containers',
    quantity: 12,
    unit: 'units',
    reorder_threshold: 10,
    created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-009',
    owner_id: 'demo-urban',
    item_name: 'Drainage Saucers (20cm)',
    category: 'Containers',
    quantity: 18,
    unit: 'units',
    reorder_threshold: 15,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-010',
    owner_id: 'demo-urban',
    item_name: 'Self-Watering Pots',
    category: 'Containers',
    quantity: 8,
    unit: 'units',
    reorder_threshold: 6,
    created_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // SOIL & AMENDMENTS (4 items)
  {
    id: 'urban-011',
    owner_id: 'demo-urban',
    item_name: 'Potting Soil Mix (40L)',
    category: 'Soil & Amendments',
    quantity: 25,
    unit: 'liters',
    reorder_threshold: 30,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-012',
    owner_id: 'demo-urban',
    item_name: 'Perlite (Soil Amendment)',
    category: 'Soil & Amendments',
    quantity: 10,
    unit: 'liters',
    reorder_threshold: 8,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-013',
    owner_id: 'demo-urban',
    item_name: 'Coco Coir (Compressed)',
    category: 'Soil & Amendments',
    quantity: 8,
    unit: 'blocks',
    reorder_threshold: 10,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-014',
    owner_id: 'demo-urban',
    item_name: 'Mulch Chips (Indoor)',
    category: 'Soil & Amendments',
    quantity: 15,
    unit: 'liters',
    reorder_threshold: 12,
    created_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // FERTILIZERS (4 items)
  {
    id: 'urban-015',
    owner_id: 'demo-urban',
    item_name: 'Organic Fertilizer Pellets (2kg)',
    category: 'Fertilizers',
    quantity: 5,
    unit: 'packs',
    reorder_threshold: 10,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-016',
    owner_id: 'demo-urban',
    item_name: 'Liquid Plant Food (500ml)',
    category: 'Fertilizers',
    quantity: 12,
    unit: 'bottles',
    reorder_threshold: 10,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-017',
    owner_id: 'demo-urban',
    item_name: 'Slow-Release Fertilizer Sticks',
    category: 'Fertilizers',
    quantity: 30,
    unit: 'sticks',
    reorder_threshold: 25,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-018',
    owner_id: 'demo-urban',
    item_name: 'Vegetable Fertilizer (1kg)',
    category: 'Fertilizers',
    quantity: 8,
    unit: 'packs',
    reorder_threshold: 6,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // TOOLS (5 items)
  {
    id: 'urban-019',
    owner_id: 'demo-urban',
    item_name: 'Hand Pruner Shears',
    category: 'Tools',
    quantity: 4,
    unit: 'units',
    reorder_threshold: 3,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-020',
    owner_id: 'demo-urban',
    item_name: 'Watering Can (2L)',
    category: 'Tools',
    quantity: 3,
    unit: 'units',
    reorder_threshold: 2,
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-021',
    owner_id: 'demo-urban',
    item_name: 'Plant Mister Spray Bottle',
    category: 'Tools',
    quantity: 6,
    unit: 'units',
    reorder_threshold: 4,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-022',
    owner_id: 'demo-urban',
    item_name: 'Soil Moisture Meter',
    category: 'Tools',
    quantity: 5,
    unit: 'units',
    reorder_threshold: 3,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-023',
    owner_id: 'demo-urban',
    item_name: 'Small Trowel',
    category: 'Tools',
    quantity: 7,
    unit: 'units',
    reorder_threshold: 5,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // EQUIPMENT (3 items)
  {
    id: 'urban-024',
    owner_id: 'demo-urban',
    item_name: 'LED Grow Light (20W)',
    category: 'Equipment',
    quantity: 2,
    unit: 'units',
    reorder_threshold: 1,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-025',
    owner_id: 'demo-urban',
    item_name: 'Grow Light Stand',
    category: 'Equipment',
    quantity: 1,
    unit: 'units',
    reorder_threshold: 1,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-026',
    owner_id: 'demo-urban',
    item_name: 'Small Water Fountain Pump',
    category: 'Equipment',
    quantity: 1,
    unit: 'units',
    reorder_threshold: 1,
    created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ACCESSORIES (4 items)
  {
    id: 'urban-027',
    owner_id: 'demo-urban',
    item_name: 'Plant Labels & Markers',
    category: 'Accessories',
    quantity: 50,
    unit: 'units',
    reorder_threshold: 40,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-028',
    owner_id: 'demo-urban',
    item_name: 'Moss Poles (Plant Support)',
    category: 'Accessories',
    quantity: 8,
    unit: 'units',
    reorder_threshold: 6,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-029',
    owner_id: 'demo-urban',
    item_name: 'Plant Climbing Trellis',
    category: 'Accessories',
    quantity: 6,
    unit: 'units',
    reorder_threshold: 4,
    created_at: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-030',
    owner_id: 'demo-urban',
    item_name: 'Twine/String (Natural)',
    category: 'Accessories',
    quantity: 10,
    unit: 'rolls',
    reorder_threshold: 8,
    created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // PEST CONTROL (3 items)
  {
    id: 'urban-031',
    owner_id: 'demo-urban',
    item_name: 'Insecticidal Soap (500ml)',
    category: 'Pest Control',
    quantity: 2,
    unit: 'bottles',
    reorder_threshold: 3,
    created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-032',
    owner_id: 'demo-urban',
    item_name: 'Neem Oil Spray',
    category: 'Pest Control',
    quantity: 3,
    unit: 'bottles',
    reorder_threshold: 2,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-033',
    owner_id: 'demo-urban',
    item_name: 'Sticky Trap Sheets',
    category: 'Pest Control',
    quantity: 24,
    unit: 'sheets',
    reorder_threshold: 20,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // WATERING (2 items)
  {
    id: 'urban-034',
    owner_id: 'demo-urban',
    item_name: 'Drip Watering System',
    category: 'Watering',
    quantity: 2,
    unit: 'units',
    reorder_threshold: 1,
    created_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'urban-035',
    owner_id: 'demo-urban',
    item_name: 'Water Globes (Plant Watering)',
    category: 'Watering',
    quantity: 8,
    unit: 'units',
    reorder_threshold: 6,
    created_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Combined data for easy access
export const ALL_DEMO_INVENTORY = [...DEMO_RURAL_INVENTORY, ...DEMO_URBAN_INVENTORY];

// Export by farm type
export const getDemoInventoryByFarmType = (farmType: 'rural' | 'urban' | 'both') => {
  if (farmType === 'rural') return DEMO_RURAL_INVENTORY;
  if (farmType === 'urban') return DEMO_URBAN_INVENTORY;
  return ALL_DEMO_INVENTORY;
};
